# Config de hyprpaper
# Cambia esta ruta por la imagen que quieras usar.
# Ejemplo recomendado:
#   /home/krate/Pictures/Wallpapers/default.jpg

preload = /home/krate/Pictures/Wallpapers/default.jpg

# Aplica el wallpaper al monitor principal del laptop.
wallpaper = eDP-1,/home/krate/Pictures/Wallpapers/default.jpg

# Opcional: habilita el control por IPC para cambiar wallpapers en caliente.
ipc = on

# Opcional: evita que hyprpaper muestre el splash al iniciar.
splash = false
